spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurante
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080