spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devrestaurante
    username: root
    password: rA&Jc5Xf9d!h!YSK
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080